In [ ]:
# Import necessary libraries
import gym
import numpy as np
import matplotlib.pyplot as plt
import math
import time

# Initialize the Gym Pendulum environment
env = gym.make('Pendulum-v1', g=2, render_mode='human')

# Define PID controller parameters
Kp = 0.4  # Proportional gain
Ki = 0  # Integral gain
Kd = 3 # Derivative gain

# Define simulation parameters
num_episodes = 1
max_steps = 200  # Number of steps per episode

setpoint = 0 # Setpoint in radians

# Data storage for plotting
time_history = []
theta_history = []
omega_history = []
torque_history = []

# initialize the error, integral, and derivative terms
error = 0
integral = 0
derivative = 0
prev_error = 0


# Control loop
for episode in range(num_episodes):
    state, _ = env.reset(seed=42)
    print(state)
    start_time = time.time()
    
    for step in range(max_steps):
        # Extract state components
        cos_theta, sin_theta, vel = state
        theta = math.atan2(sin_theta, cos_theta)  # Calculate theta in radians
        print(state)
        print(theta)

        # Update PID controller
        current_time = time.time() - start_time

        error = setpoint - theta
        integral += error
        derivative = (error - prev_error)/current_time
        prev_error = error

        output = (Kp * error) + (Ki * integral * current_time) + (Kd * derivative)
        
        # Clamp torque to environment's action space limits
        torque = np.clip(output, env.action_space.low[0], env.action_space.high[0])
        print(torque)
        
        # Apply action to the environment
        action = [torque]
        state, reward, done, _, info = env.step(action)
        
        # Record data
        time_history.append(current_time)
        theta_history.append(math.degrees(theta))     # Convert to degrees for readability
        omega_history.append(math.degrees(vel)) # Convert to degrees/s
        torque_history.append(torque)
        
        # Optional: Print debug information
        # print(f"Step: {step}, Time: {current_time:.2f}s, Theta: {math.degrees(theta):.2f}°, Omega: {math.degrees(theta_dot):.2f}°/s, Torque: {torque:.2f}")
        
        # Sleep to match the sample time (optional)
        time.sleep(0.01)
        
        if done:
            break

# Close the environment
env.close()

# Plotting the results
plt.figure(figsize=(15, 10))

# Plot Theta (Angle)
plt.subplot(3, 1, 1)
plt.plot(time_history, theta_history, label='Theta (degrees)')
plt.axhline(y=setpoint, color='r', linestyle='--', label='Setpoint')
plt.title('Pendulum Angle Over Time')
plt.ylabel('Angle (°)')
plt.legend()
plt.grid(True)

# Plot Omega (Angular Velocity)
plt.subplot(3, 1, 2)
plt.plot(time_history, omega_history, label='Omega (degrees/s)', color='g')
plt.title('Pendulum Angular Velocity Over Time')
plt.ylabel('Angular Velocity (°/s)')
plt.legend()
plt.grid(True)

# Plot Torque
plt.subplot(3, 1, 3)
plt.plot(time_history, torque_history, label='Control Torque (N·m)', color='m')
plt.title('Control Torque Over Time')
plt.xlabel('Time (s)')
plt.ylabel('Torque (N·m)')
plt.legend()
plt.grid(True)

plt.tight_layout()
plt.show()


2025-01-15 15:48:23.670 python[4134:10274125] +[IMKClient subclass]: chose IMKClient_Modern
2025-01-15 15:48:23.670 python[4134:10274125] +[IMKInputSession subclass]: chose IMKInputSession_Modern
/Users/denisbespalko/GitHub/2024-25b-fai2-adsai-DenysBespalko231452/.conda/lib/python3.9/site-packages/gym/utils/passive_env_checker.py:233: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):


[-0.14995256  0.9886932  -0.12224312]
[-0.14995256  0.9886932  -0.12224312]
1.7213166198075167
-2.0
[-0.13639683  0.9906543  -0.27393913]
1.7076196546116469
0.5769972307988959
[-0.13447513  0.99091697 -0.03879141]
1.7056800861926371
-0.5790499416723249
[-0.13561404  0.99076176  0.02298864]
1.7068295242726668
-0.7250984683509228
[-0.13872623  0.99033076  0.06283813]
1.7099714249436175
-0.7717444862161239
[-0.14345971  0.98965615  0.09562607]
1.7147527326807026
-0.7932738862301879
[-0.14964634  0.9887396   0.12508342]
1.721006900704351
-0.8067432340980718
[-0.15717527  0.9875707   0.15238287]
1.7286260492207266
-0.8164319409552293
[-0.16596095  0.9861323   0.17805368]
1.7375287247781879
-0.822955295830604
[-0.17593835  0.98440117  0.20253024]
1.7476552395221876
-0.8287022551264447
[-0.18704498  0.98235136  0.22588508]
1.7589494936203616
-0.8346036286328181
[-0.19921376  0.97995603  0.24804723]
1.7713518641531318
-0.8393326602784996
[-0.21238263  0.97718656  0.26914075]
1.7848089025063554